### ISSUE TITLE
closing for loop too early

### ISSUE THREAD

**Issue by qyx268** [BradGreig/21CMMC#5]
hey @BradGreig  I just spot a bug (I think...) when `USE_MASS_DEPENDENT_ZETA=False`. It's here:

https://github.com/BradGreig/21CMMC/blob/73493ba96aec79a1e33ee9ef31663baa66aea0e0/21CMMC_SourceCode/Programs/drive_21cmMC_streamlined.c#L1787

I think you close the for loop earlier, which ends up using `dfcoll_dz_va`l at `R_ct==0` for all cells. My simulations always needed `USE_MASS_DEPENDENT_ZETA=True`, so this never bothered me or led me to find this...

**Comment by steven-murray** [comment]
Is this an issue in the new `21cmFAST`?

**Comment by qyx268** [comment]
no, it is not. That's the first thing I checked...

**Comment by BradGreig** [comment]
Hmm, well spotted @qyx268! Seems have come in when I tried to add backwards compatibility. Never done anything with this section of the code. I'll update the code

**Comment by BradGreig** [comment]
This has been updated in the latest commit
